project:
  type: website

website:
  title: "Data Automation Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching_materials/intro.qmd
        text: Introduction
      - href: teaching_materials/fetching.qmd
        text: Fetching Data

format:
  revealjs:
    theme: simple
    transition: fade
    slide-number: true
    incremental: true
    toc: true

execute:
  echo: true
  warning: false
