project:
  type: website

website:
  title: "Data Automation Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching_materials/intro.qmd
        text: Introduction
      - href: teaching_materials/fetching.qmd
        text: Fetching Data
      - href: teaching_materials/example1_sdmx.qmd
        text: Example 1 (SDMX)
      - href: teaching_materials/example2_statistics_estonia.qmd
        text: Example 2 (Estonia)
      - href: teaching_materials/reporting.qmd
        text: Reporting
      - href: about.qmd
        text: About

format:
  revealjs:
    theme: simple
    transition: fade
    slide-number: true
    incremental: true
    toc: true

execute:
  echo: true
  warning: false
